### ISSUE TITLE
Swift Package Manager error

### ISSUE THREAD

**Issue by marcheimendinger** [TimOliver/TORoundedButton#33] opened 2020-02-13 22:20 UTC
While trying to install the library using Swift Package Manager in Xcode, I get an error.

> TORoundedButton has no Package.swift manifest for version 1.1.2

<img width="655" alt="Screenshot 2020-02-13 at 23 17 12" src="https://user-images.githubusercontent.com/43568598/74483746-575e4900-4eb7-11ea-8e34-6f1f51c40d69.png">

**Comment by TimOliver** [comment] 2020-02-24 06:27
Thanks for the report @marcheimendinger! Unfortunately, I don't have time to look at this at the moment. If you can help at all, that'd be much appreciated. :)

**Comment by woxtu** [comment] 2020-12-09 09:39
@TimOliver The latest release doesn't include the package manifest yet, so you need to create a new tag to fix that.

**Comment by TimOliver** [comment] 2020-12-12 04:46
@woxtu Oh! That's easy enough! I'll do that when I get the chance. Thanks!

**Comment by TimOliver** [comment] 2020-12-12 08:08
Alrighty! I've updated the project for Xcode 12, and refined the SwiftPM configuration. I tested it in a local project and it seems to be working fine. I've pushed v1.1.3 with these changes.

I'm closing this off now. If the issue is still persisting, please make a new issue so we can start fresh.

Thanks!

**Closed as completed by TimOliver** 2020-12-12 08:08 UTC
Labels: bug, help wanted
